name = "agora"
main = "src/index.ts"
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat_v2", "nodejs_als"]

[observability.logs]
enabled = true
invocation_logs = false

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "Agora"
id = "66899780ce2a4ddd8be011f54d897f89"
